#include<iostream>
using namespace std;
main()
{
    string word;
    cout<<"Enter word : ";
    cin>>word;
    //loop that returns next character of alphabet
    for(int idx=0;word[idx]!='\0';idx++)
    {
        if(word[idx]=='a')
        {
            cout<<'b';
        }
        if(word[idx]=='b')
        {
            cout<<'c';
        }
        if(word[idx]=='c')
        {
            cout<<'d';
        }
        if(word[idx]=='d')
        {
            cout<<'e';
        }
        if(word[idx]=='e')
        {
            cout<<'f';
        }
        if(word[idx]=='f')
        {
            cout<<'g';
        }
        if(word[idx]=='g')
        {
            cout<<'h';
        }
        if(word[idx]=='h')
        {
            cout<<'i';
        }
        if(word[idx]=='i')
        {
            cout<<'j';
        }
        if(word[idx]=='j')
        {
            cout<<'k';
        }
        if(word[idx]=='k')
        {
            cout<<'l';
        }
        if(word[idx]=='l')
        {
            cout<<'m';
        }
        if(word[idx]=='m')
        {
            cout<<'n';
        }
        if(word[idx]=='n')
        {
            cout<<'o';
        }
        if(word[idx]=='o')
        {
            cout<<'p';
        }
        if(word[idx]=='p')
        {
            cout<<'q';
        }
        if(word[idx]=='q')
        {
            cout<<'v';
        }
        if(word[idx]=='v')
        {
            cout<<'w';
        }
        if(word[idx]=='w')
        {
            cout<<'x';
        }
        if(word[idx]=='x')
        {
            cout<<'y';
        }
        if(word[idx]=='y')
        {
            cout<<'z';
        }
        if(word[idx]=='z')
        {
            cout<<'a';
        }
    }
}